/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddTutorRouteImport } from './routes/add-tutor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorsIdRouteImport } from './routes/tutors.$id'

const AddTutorRoute = AddTutorRouteImport.update({
  id: '/add-tutor',
  path: '/add-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsIdRoute = TutorsIdRouteImport.update({
  id: '/tutors/$id',
  path: '/tutors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-tutor': typeof AddTutorRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-tutor': typeof AddTutorRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-tutor': typeof AddTutorRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-tutor' | '/tutors/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-tutor' | '/tutors/$id'
  id: '__root__' | '/' | '/add-tutor' | '/tutors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddTutorRoute: typeof AddTutorRoute
  TutorsIdRoute: typeof TutorsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add-tutor': {
      id: '/add-tutor'
      path: '/add-tutor'
      fullPath: '/add-tutor'
      preLoaderRoute: typeof AddTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/$id': {
      id: '/tutors/$id'
      path: '/tutors/$id'
      fullPath: '/tutors/$id'
      preLoaderRoute: typeof TutorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddTutorRoute: AddTutorRoute,
  TutorsIdRoute: TutorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
