/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FindTutorRouteImport } from './routes/find-tutor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorsIdRouteImport } from './routes/tutors.$id'
import { Route as AuthenticatedAddTutorRouteImport } from './routes/_authenticated/add-tutor'

const FindTutorRoute = FindTutorRouteImport.update({
  id: '/find-tutor',
  path: '/find-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsIdRoute = TutorsIdRouteImport.update({
  id: '/tutors/$id',
  path: '/tutors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAddTutorRoute = AuthenticatedAddTutorRouteImport.update({
  id: '/add-tutor',
  path: '/add-tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find-tutor': typeof FindTutorRoute
  '/add-tutor': typeof AuthenticatedAddTutorRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find-tutor': typeof FindTutorRoute
  '/add-tutor': typeof AuthenticatedAddTutorRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/find-tutor': typeof FindTutorRoute
  '/_authenticated/add-tutor': typeof AuthenticatedAddTutorRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/find-tutor' | '/add-tutor' | '/tutors/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/find-tutor' | '/add-tutor' | '/tutors/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/find-tutor'
    | '/_authenticated/add-tutor'
    | '/tutors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FindTutorRoute: typeof FindTutorRoute
  TutorsIdRoute: typeof TutorsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/find-tutor': {
      id: '/find-tutor'
      path: '/find-tutor'
      fullPath: '/find-tutor'
      preLoaderRoute: typeof FindTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/$id': {
      id: '/tutors/$id'
      path: '/tutors/$id'
      fullPath: '/tutors/$id'
      preLoaderRoute: typeof TutorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/add-tutor': {
      id: '/_authenticated/add-tutor'
      path: '/add-tutor'
      fullPath: '/add-tutor'
      preLoaderRoute: typeof AuthenticatedAddTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddTutorRoute: typeof AuthenticatedAddTutorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddTutorRoute: AuthenticatedAddTutorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FindTutorRoute: FindTutorRoute,
  TutorsIdRoute: TutorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
